/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import { useEffect, useState } from "react";
import type { Mailbox } from "@/lib/mail-types";

export default function MailboxesPage() {
  const [items, setItems] = useState<Mailbox[]>([]); const [editing, setEditing] = useState<string | null>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [prompt, setPrompt] = useState(""); const [ai, setAi] = useState(true); const [message, setMessage] = useState("");
  const load = () => fetch("/api/mailboxes").then((response) => response.json()).then(setItems); useEffect(() => { void load(); }, []);
  const reset = () => { setEditing(null); setEmail(""); setPassword(""); setPrompt(""); setAi(true); };
  const save = async () => { const payload = { email, password, prompt, ai_enabled: ai }; const url = editing ? `/api/mailboxes/${editing}` : "/api/mailboxes"; const response = await fetch(url, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (response.ok) { reset(); void load(); setMessage("Mailbox saved."); } else { const data = await response.json(); setMessage(data.error || "Unable to save mailbox."); } };
  const edit = (mailbox: Mailbox) => { setEditing(mailbox.id); setEmail(mailbox.email); setPrompt(mailbox.prompt || ""); setAi(mailbox.ai_enabled); setPassword(""); };
  const test = async (id: string, type: "imap" | "smtp") => { const response = await fetch(`/api/mailboxes/${id}/test`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type }) }); const data = await response.json(); setMessage(data.message || data.error); };
  return <main className="mail-shell"><header className="topbar"><a className="brand" href="/">inbox<span>draft</span></a><nav><a href="/">Drafts</a><a className="active" href="/mailboxes">Mailboxes</a><a href="/settings">Settings</a></nav></header><section className="content"><div className="page-heading"><div><p className="eyebrow">Purelymail connections</p><h1>Mailboxes</h1><p className="lede">Connect up to 20 inboxes. Passwords are encrypted and never returned to the browser.</p></div><span className="count">{items.length} / 20</span></div><div className="mailbox-layout"><div className="settings-card"><h2>{editing ? "Edit mailbox" : "Add mailbox"}</h2><label htmlFor="email">Email address</label><input id="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="sales@example.com" /><label htmlFor="password">Password {editing && <small>leave blank to keep current</small>}</label><input id="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} /><label className="check"><input type="checkbox" checked={ai} onChange={(event) => setAi(event.target.checked)} /> AI drafting enabled</label><label htmlFor="prompt">AI instructions</label><textarea id="prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Reply professionally and concisely..." /><div className="actions"><button className="button primary" onClick={() => void save()}>{editing ? "Save changes" : "Add mailbox"}</button>{editing && <button className="button ghost" onClick={reset}>Cancel</button>}</div>{message && <p className="notice">{message}</p>}</div><div className="mailbox-list">{items.map((mailbox) => <article className="mailbox-row" key={mailbox.id}><div><strong>{mailbox.email}</strong><span>{mailbox.ai_enabled ? "AI enabled" : "AI paused"}</span></div><div className="row-actions"><button onClick={() => edit(mailbox)}>Edit</button><button onClick={() => void test(mailbox.id, "imap")}>Test IMAP</button><button onClick={() => void test(mailbox.id, "smtp")}>Test SMTP</button><button className="delete-link" onClick={() => { if (window.confirm("Delete this mailbox?")) fetch(`/api/mailboxes/${mailbox.id}`, { method: "DELETE" }).then(() => void load()); }}>Delete</button></div></article>)}</div></div></section></main>;
}
